default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: movie_booking_system_development
test:
  <<: *default
  database: movie_booking_system_test
production:
  <<: *default
  database: movie_booking_system_production