development:
  clients:
    default:
      database: heroku_ghl68wnz
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: heroku_ghl68wnz
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
    clients:
      default:
          uri: <%= ENV['MONGODB_URI'] %>