development:
  clients:
    default:
      database: movie_booking_system_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: movie_booking_system_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
    clients:
      default:
          uri: <%= ENV['MONGODB_URI'] %>