development:
  clients:
    default:
      database: movie_booking_system_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: movie_booking_system_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
    clients:
      default:
        uri: 'mongodb://heroku_6fp6r2kt:g436auh6pqgtc7hirq3o707h14@ds153593.mlab.com:53593/heroku_6fp6r2kt'
        database: movie_booking_system_production
        hosts:
          - localhost:27017
        options:
          skip_version_check: true
        safe: true